[project]
title = "Netflix Wrapped"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[branding]
name = "Preswald Project"
logo = "images/Netflix-logo.png"
favicon = "ğŸï¸"
primaryColor = "#F89613"

[data.netflix_titles]
type = "csv"
path = "data/netflix_titles.csv"


[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
